### PR TITLE
✨ Moved the themes to a separate menu page

### LINKED ISSUE #139: Curated themes are hidden on small screens
We have now 5 curated themes and the last one gets hidden in small screens. 

Most likely add another menu section called themes which is then a page with a list of themes.

We will also use this in the future as the page to create your own.

### PR DESCRIPTION
**Pull request by Komposten**
Fixed #139. Still a work in progress.

Currently I'm using a Wrap widget to lay out the theme previews. However, since the previews have slightly differing width (due to their names being different), it doesn't look too good. Anyone know how I can force the previews to all have the same width as the widest one to align them nicely, or if there is another layout I can use that does this automatically (e.g. but still allows for a dynamic column count to accommodate different screen sizes and orientations)?

### CODE REVIEW

**Comment by lifenautjoe** [comment]
I believe you can use https://flutter.dev/docs/cookbook/lists/grid-lists for this

**Comment by Komposten** [comment]
I have looked at GridView, but wasn't sure if I could get it to adapt the number of columns based on the available width and the width of the children. Will take a closer look at SliverGridDelegate and see if I can get something out of that.

**Comment by Komposten** [comment]
Updated to use GridView instead. Currently it uses a constant max column width of 120 logical pixels, which works on the 4 Android devices I have tested it on. I would much rather use a dynamic columns that adapt to the width of the actual OBThemePreviews, but I haven't found a way to achieve that for a GridView.

Note: Current solution will not work for long theme names (i.e. exceeding 120 logical pixels), so I'm still looking for a better way of doing this...

**Comment by uiboy** [comment]
@Komposten just took a look at this, if you set the alignment of the text in the `theme_preview.dart` to be center aligned, it already makes things better for long names (but with individual words less than < 120 logical pixels) . I think this would suffice. 
```
    OBText(
                    theme.name,
                    size: OBTextSize.small,
                    style: TextStyle(fontWeight: FontWeight.bold),
                    textAlign: TextAlign.center,  
                  )
```
However, If you want to solve for the case where the entire column should expand to allow really long individual words in one theme, then perhaps you can try laying out the themes with a custom `Row` which in turn has three `Columns` .. then if you wrap each column with `InstrinsicWidth` 
it should expland it to the widest child. Not sure if it will work but worth a shot.
```
return  Row( children: [
      IntrinsicWidth(
        child: Column(...)   //col 1
     ), 
      IntrinsicWidth(
        child: Column(...)  // col 2
     ), 
     IntrinsicWidth(
        child: Column(...)  // col3
     ), 
 ...
```

**Comment by Komposten** [comment]
Realised that the default cell aspect ratio was fine for up to three lines of text... 🤦‍♂️
The last commit centres text and allows it to wrap up to three lines. If a word doesn't fit on a single line it's split over two.

Screenshot for example of 3 lines:
image

I think this should be ready for a merge now. Have tested on three devices with different resolutions (2 16:9 phones and one 4:3 tablet).

**Comment by uiboy** [comment]
Yes in my original comment I meant using a custom `Row` and `Column` layout instead of `GridView`, but it could be overkill and I only suggested it in case you really really wanted to fix that issue 😄

**Comment by uiboy** [comment]
Was talking to Joel about this, the PR is ready to go. We were thinking one small change, the themes are currently immediately visible when someone navigates to the last menu icon. Now that we have it behind a menu item, new users might not notice immediately that they can set themes, which is a feature liked by many. 

So to make that "themes" item stand out a bit, can we change the paintbrush icon of the themes item to take the primary color of the current theme. That would make it noticeable :)

**Comment by Komposten** [comment]
image
Like this? 🙂

**Comment by lifenautjoe** [comment]
Hmmmm perhaps just default color is fine, this kinda looks like it’s the
active tile.

Thanks for trying it out though 🙏. I’ll take a look at this later today
and get it merged.

**Comment by lifenautjoe** [comment]
Hi Jacob! I cannot push to your branch, you could give me permission? I believe it's a setting somewhere. Fixed a couple of small style issues, for the rest all looks good!

**Comment by lifenautjoe** [comment]
Oh wait that worked, nevermind!

**Comment by lifenautjoe** [comment]
Merging now, thank you!

**Pull request merged**
