### PR TITLE
♻️ migrate codebase to nullsafety

### PR DESCRIPTION
**Pull request by jozsefsallai**
This was/is a mostly manual migration*, so it's very likely that there are bugs here and there, but overall the migration is **complete**, now it's time for **testing**. I'm still testing as many features of the app as possible, to make sure everything works as intended. So far, apart from some smaller issues I've noticed, everything works fine. If you want to help debug things, you can build the app yourself report bugs back to me.

Sometimes there's some lag going on in the debug build** but that might be because it's not optimized and has a lot of debug symbols left in, which makes it slower.

When building the app, you have to use the `--no-sound-null-safety` flag for now, as some libraries are not yet migrated to support nullsafety (such as the OneSignal SDK). The vscode build tasks include this flag by default.

*) I tried using the Dart migration tool but I couldn't get it to work at all. Also, I preferred to have this be manual for the most part, since trusting machines to automagically migrate such a large codebase is not necessarily a good idea because it could result in lots of debugging.

**) Haven't used the production build more thoroughly just yet.

P.S.: the oldest (largest) commit was originally split into multiple smaller commits, but I rebased it so it's all clean and tidy :)

Relevant issue: #546 

## Todo list

- [x] app ignores link preview preferences until you change them
- [x] images in link previews don't show up (weird because it used to work)
- [x] onesignal_flutter was migrated over, we can upgrade it
- [x] clicking on a community from hashtag search (probably other post streams) displays a nullcheck operator error for a second, then it displays the community
- [x] overflow error in user stream: https://i.imgur.com/1Y6OzCF.png
- [x] default profile pic doesn't show up in community (if a user has no profile pic): https://i.imgur.com/bLJ3Aq9.png
- [x] adding administrator displays "Unknown error" but adds the admin anyway (moderators and blocked users don't have this issue)
- [x] ~~this very questionable overflow: https://i.imgur.com/fiqv7jM.jpg~~ (we can prooooobably ignore this)
- [x] tapping on "new circle" in the "add user to connections" bottom sheet results in this error (lists don't have this issue and the new circle modal works when opened from the menu): https://i.imgur.com/XwekOvk.jpg

### CODE REVIEW

**Comment by jozsefsallai** [comment]
If you'd like to help testing the app post-migration but don't want to build it yourself, you can use the following APK: https://s3-us-west-1.amazonaws.com/sallai/app-production-debug.apk (I don't have an iOS device, so I can't provide with an iOS build, sorry) 🎉

**Comment by jozsefsallai** [comment]
Uploaded a new apk with all of the bugs from the initial todo list fixed. The download link should be the same.

**Comment by vituocgia** [comment]
Good job man! I'm going to test on the iOS now...

**Comment by jozsefsallai** [comment]
Thanks @vituocgia! Lemme know if you've encountered any bugs!

**Pull request merged**
