### PR TITLE
:sparkles: Swipe up to dismiss photo view box #79

### PR DESCRIPTION
**Pull request by cyriana**
I added swipedetector to the projects depedencies and implemented the possibilty to close the PhotoView with swiping up or down. I also tested if it interferse with zooming, which seems not to be the case. I could not test it on iphone.

### CODE REVIEW

**Comment by lifenautjoe** [comment]
Looks good, only thing is that it would be great to have some visual feedback on this. Perhaps drag the image upwards or downwards as we swipe. 

I tried to do this before with a `Dismissable` element with vertical direction but the gestures of the zoom box were getting all messed up. 

Some other ideas on this?

**Comment by lifenautjoe** [comment]
P.S. It's totally okay if this is not doable for now as it's your first intro into Flutter, I'll also see what I can do with the new swipe library on the weekend.

**Comment by cyriana** [comment]
I tried Dismissable, too. Wasn't really promissing. Any ideas on this, someone?

**Comment by lifenautjoe** [comment]
There's also https://docs.flutter.io/flutter/widgets/Draggable-class.html 🤔 , never used it though

**Comment by uiboy** [comment]
`GestureDetector` has a bunch of callbacks for fine grained control for how to provide visual feedback depending on what the user is doing on the screen. 
eg. below for some ideass... but flutters documentation has much more https://docs.flutter.io/flutter/widgets/GestureDetector-class.html 
```
  GestureDetector(
     onPanStart: (DragStartDetails details) {
      initial = details.globalPosition.dy;   //initial place where user began to swipe
     },
     onPanUpdate: (DragUpdateDetails details) {
      distance= details.globalPosition.dy - initial;   // determine if user is swiping up or down, and move image with it
     },
     onPanEnd: (DragEndDetails details) {
      initial = 0.0; 
     // here we could dismiss the image with an animation if we feel user has dragged enough 
});
```
So maybe this helps? We can also try and add the slight rotation as the user swipes

**Comment by cyriana** [comment]
Could you please give me an example how the slight rotation looks like. I can't imagine. Maybe I will have look into this tomorrow or next week.

**Comment by uiboy** [comment]
Unfortunately github doesnt support .mp4 files... so zipped the video i made from slack
[File from iOS.MP4.zip](https://github.com/OpenbookOrg/openbook-app/files/3025576/File.from.iOS.MP4.zip)

**Comment by cyriana** [comment]
Ah wow this looks completly different on Android, haha. That's why i didn't know, what you mean.

**Comment by uiboy** [comment]
Oh haha .... wonder how it looks on Android 🤔

**Comment by cyriana** [comment]
Like in openbook right now.

**Comment by cyriana** [comment]
I just commited the changes for the animation when dismissing the Photo View. There's still a bug with the backButton. I think it's this one: https://github.com/OpenbookOrg/openbook-app/issues/124

**Comment by uiboy** [comment]
Just checked out the animation on the phone. Both Joel and I love it. Good stuff man 👍We did notice that the dismiss doesn't work if u randomly swipe in a diagonal direction.. I think a lot of users will not precisely swipe up / down.. can we maybe try using the `GestureDetector` instead of the package 😬 I know its complicated, but it will make the UX so much friendlier, so take ur sweet time. Also can we make the animation a just a tad bit faster, currently it rolls away, then the screen fades out revealing the timeline underneath, so the user has to wait a bit.

**Comment by cyriana** [comment]
Found a bit time for Improvement. I hope it is better now.

**Comment by uiboy** [comment]
@cyriana will check, thanks :)

**Comment by uiboy** [comment]
Alright @cyriana so inspired by this PR, i got the slack type animation working on dismissible photos more or less like slack. I wanted to create a PR to this branch, but yday we discovered somehow the commit history on master was messed up, so to start fresh i created another branch. 
Take a look at this, here
https://github.com/OpenbookOrg/openbook-app/pull/227

**Comment by cyriana** [comment]
Nice. I will take a look how you managed this.

**Pull request closed without merging**
