### PR TITLE
✨ Add Light Cinnabar and Space Cinnabar theme

### PR DESCRIPTION
**Pull request by WouterJanson**
Adds two new themes. A beautiful deep red theme in a Light and Space variant.
Would still need the preview image 😅

### CODE REVIEW

**Comment by lifenautjoe** [comment]
Hi Wouter! Can you change the target branch to develop and take some screenshots to paste here?

In the meanwhile here are the previews https://send.firefox.com/download/7b9666f97d/#LDlwrdILZ3nka88uN4y5SA

**Comment by WouterJanson** [comment]
Hi Joel,

I've changed the base branch.
Here are two screenshots, haven't been able to make others. Because I still have to run my own API or connected the app to the live one. 😅

Ohh, and the firefox send link is password protected.

1jiCBh30h5vZo1cFbo8Rjxc--5I04C4cu=w600-k-iv1
1-0qIKKn82tiVNzYPvoAPtISW8tw1wMFo=w3840-h2274-iv1

**Comment by lifenautjoe** [comment]
Looks very fancy! I'll add the previews and ship it in an upcoming release :) Thanks for the first ever contribution to the openbook-app codebase!

**Comment by lifenautjoe** [comment]
Hey Wouter! Added the preview files and tweaked one of the colors a little bit so mentions & links are more easy on the eyes when with the dark version

**Comment by WouterJanson** [comment]
No problems, I wasn’t able to fully test it because I only had one screen to look at 👀

**Pull request merged**
